### ISSUE TITLE
Cannot find module lodash/object/defaults

### ISSUE THREAD

**Issue by vorg** [runemadsen/rune.font.js#1]
I'm having problems running rune.font.js from npm with newest rune.js. Is it because rune.font.js requires rune.js@0.2.3 and i'm using rune.js@1.0.2?

<img width="331" alt="screen shot 2017-09-11 at 21 37 49" src="https://user-images.githubusercontent.com/171001/30295725-87303a54-9739-11e7-994b-a21c74602983.png">

**Comment by runemadsen** [comment]
Are you running Rune.js in Node or in a browser? If Node, make sure that
you have 'npm install'ed

**Comment by runemadsen** [comment]
I just published `0.0.4` which should solve this problem. Sorry for the troubles! Doing a sweep of bug fixes and updates to Rune.js right now.
